---
title: "Syllabus"
subtitle: "Syllabus, entry requirements and selection criteria"
date: ""
toc: false
number-sections: false
sidebar: false
format: html
---

::: {.panel-tabset}

## Syllabus

- Data processing and analyses for differential DNA methylation with Illumina 
EPIC arrays and Bisulfite-seq 
- ChIP-seq: overview of the methods, peak calling, peak independent/dependent 
quality metrics, joint visualization of different chromatin marks
- ATAC-seq: peak calling, peak independent/dependent quality metrics, 
differential accessibility analysis
- Integrative visualizations of epigenomics datasets
- Motif analyses: PWMs, motif enrichment, regression-based approaches
- Functional analyses, including finding nearest genes and custom features, 
GO terms and Reactome pathways enrichment
- Introduction to analysis of single cell omics such as scATAC-seq


## Entry requirements

- To be able to follow the tutorials:
  - BYOL, bring your own laptop with R and RStudio installed
  - Basic knowledge in Linux
  - Basic R programming experience

- To make the learning experience easier:
  - Experience working on the SNIC center Uppmax or another HPC
  - Previous experience with NGS data analyses
  - Completing NBIS workshops “Introduction to Bioinformatics using NGS data” 
  and “R Programming Foundations for Life Scientists” or equivalent

## Selection criteria

- Due to limited capacity the workshop can accommodate maximum of 25 
participants. If we receive more applications, participants will be selected 
based on several criteria. Selection criteria include correct entry 
requirements, motivation to attend the course as well as gender and 
geographical balance.
- NBIS prioritizes academic participants, especially PhD students affiliated 
with Swedish universities. We warmly welcome international and/or non-academic 
participants when we have seats available and the requirements criteria are met.


:::
